export { default as Landing } from "./Landing"
export { default as MainLogoPage } from "./MainLogo"
export { default as BrandAssetsPage } from "./BrandAssets"
export { default as TechPage } from "./Tech"
export { default as RoadMapPage } from "./RoadMap"
export { default as CommunityPage } from "./Community"
export { default as NewsPage } from "./News"
